version: '3.9'

services:
    
  client:
    build: ./client
    network_mode: "host"
    volumes:
      - /:/mount:ro
      - ${XAUTHORITY}:/root/.Xauthority
    devices:
      - /dev/dri:/dev/dri
    environment:
      DISPLAY: ${DISPLAY}

  server:
    build: ./server
    network_mode: "host"
    volumes:
      - /:/mount:ro
