version: '3.9'

services:
    
  client:
    build: ./client
    network_mode: "host"
    volumes:
      - /:/mount:ro

  server:
    build: ./server
    network_mode: "host"
    volumes:
      - /:/mount:ro